# Generated by Django 5.0.2 on 2025-04-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='in_use_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity currently in use'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total quantity of items'),
        ),
    ]
