# Generated by Django 5.0.2 on 2025-04-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_assignment_options_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='agent',
            name='contact_info',
            field=models.TextField(blank=True, help_text='Additional contact information'),
        ),
    ]
