# Generated by Django 5.0.2 on 2025-04-17 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='record_origin',
            field=models.CharField(blank=True, help_text='Indicates if the record was auto-suggested or manually created', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Optional reference to an existing agent record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agent'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='agent_name',
            field=models.CharField(help_text="Free-text field for agent's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, help_text='Optional category for classification', max_length=50, null=True),
        ),
    ]
